config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "messages#index"
  resources :messages, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  validates :images, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages

  validates :nickname, presence: true, length: { maximum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :basic_auth

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :set_message, only: [:show, :destroy]

  def index
    @messages = Message.all.order('created_at DESC')
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      redirect_to new_message_path, flash:{miss: '投稿するには画像を選択してください'}
    end
  end

  def show
  end

  def destroy
    if current_user.id == @message.user_id
      @message.destroy
    end
    redirect_to root_path
  end

  private
  def message_params
    params.require(:message).permit(:content, images: []).merge(user_id: current_user.id)
  end

  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter画像共有広場</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      a {
        text-decoration: none ;
      }
    </style>
  </head>

  <body>
    <header>
      <div class="heading">
        <h2><%= link_to 'Twitter画像共有広場', root_path %></h2>
      </div>
      <div class="navbar">
        <ul class="nav-lists">
          <% if user_signed_in? %>
            <%= link_to '新規投稿', new_message_path %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "ログイン", new_user_session_path %>
            <%= link_to "新規登録", new_user_registration_path  %>
          <% end %>
        </ul>
      </div>
      <% if user_signed_in? %>
        <div class="current_user">
          <%= "#{current_user.nickname}さん！ようこそ！" %>
        </div>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: @message, id: 'new_message', local: true do |f| %>
  <%= render "/shared/error_messages", model: f.object %>
  <%= f.text_field :content, placeholder: '何の画像？' %>
  <%= f.file_field :images, name: 'message[images][]', id: 'message_image' %>
  <%= f.submit '送信' %>
  <div id="image-list"></div>
<% end %>

<% @message.images.each do |image| %>
  <%= image_tag image, class: 'images' %>
<% end %>

app/views/messages/edit.html.erb
<h3>編集</h3>
<%= render partial: 'form' %>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="image">
    <% @messages.each do |message| %>
      <%= "投稿者 #{message.user.nickname}" %>
      <%= message.created_at %>
      <% if user_signed_in? && current_user.id == message.user_id %>
        <%= link_to '削除', message_path(message.id), method: :delete %>
      <% end %>
      <%= message.content %>
      <div>
        <% message.images.each do |image| %>
          <%= link_to message_path(message.id) do %>
            <%= image_tag image, class:'images' %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="twitter">
    <a class="twitter-timeline" data-lang="ja" data-width="300" data-theme="dark" href="https://twitter.com/kamikazenohiro1?ref_src=twsrc%5Etfw">Tweets by kamikazenohiro1</a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
</div>

app/views/messages/new.html.erb
<h2>新規投稿</h2>
  <div class='flash-message'>
    <%= flash[:miss] %>
  </div>
<%= render partial: "form" %>

app/views/messages/show.html.erb
<div class="image">
  <%= "投稿者 #{@message.user.nickname}" %>
  <%= @message.created_at %>
  <% if user_signed_in? && current_user.id == @message.user_id %>
    <%= link_to '削除', message_path(@message.id), method: :delete %>
  <% end %>
  <%= @message.content %>
  <% @message.images.each do |image| %>
    <div class="image-show">
      <%= image_tag image, class:'image-show' %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>